### ISSUE TITLE
Links in /view/ziplink include local address in some cases

### ISSUE THREAD

**Issue by nicholasnelson** [aussieshibe/ziplink.xyz#1]
Because of how HTML handles hrefs, if a URL in a ziplink doesn't include http://, localhost:3000/ziplinkid will be prepended to the URL in the ziplink view page

Suggesting we resolve this by having a protocol property for sublinks which defaults to http:// if no other protocol is provided and is prepended to the start of the href attribute

This would also allow for expansion later to include protocol specific things (seed tracking for magnet links, etc?)

![screenshot_2016-06-04_01-59-34](https://cloud.githubusercontent.com/assets/7485405/15798740/90426a38-2a82-11e6-85c8-1097094755c1.png)

**Comment by stewartmalik** [comment]
#5
