### ISSUE TITLE
Short IDs are generating as 8 characters and include dashes and underscores

### ISSUE THREAD

**Issue by stewartmalik** [aussieshibe/ziplink.xyz#6]

**Comment by nicholasnelson** [comment]
Started working on this in branch id-gen-fix

**Comment by nicholasnelson** [comment]
The current id generator, shortid, does not support custom lengths or alphabets of less than 64 characters rendering this issue impossible to fix with this id generator. We will need to either implement a custom random ID generator or use a sequential approach.
